export type IconName =
  | 'Briefcase'
  | 'Coins'
  | 'Landmark'
  | 'Store'
  | 'PlusSquare'
  | 'Utensils'
  | 'Bus'
  | 'Smartphone'
  | 'ShoppingBag'
  | 'Home'
  | 'HeartPulse'
  | 'Film'
  | 'GraduationCap'
  | 'Users'
  | 'PiggyBank'
  | 'HelpCircle'; // 미분류 아이콘 추가
